version: '3.8'

services:
  # API Gateway
  api-gateway:
    build:
      context: ../backend/api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - AUTH_SERVICE_URL=http://auth-service:3001
      - USER_SERVICE_URL=http://user-service:3002
      - RESTAURANT_SERVICE_URL=http://restaurant-service:3003
      - ORDER_SERVICE_URL=http://order-service:3004
      - PAYMENT_SERVICE_URL=http://payment-service:3005
      - DELIVERY_SERVICE_URL=http://delivery-service:3006
      - NOTIFICATION_SERVICE_URL=http://notification-service:3007
      - AI_SERVICE_URL=http://ai-service:3008
      - ANALYTICS_SERVICE_URL=http://analytics-service:3009
      - MONGO_URI=mongodb://mongo:27017/fastbite
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your-super-secret-jwt-key
    depends_on:
      - mongo
      - redis
      - auth-service
    networks:
      - fastbite-network

  # Auth Service
  auth-service:
    build:
      context: ../backend/services/auth-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGO_URI=mongodb://mongo:27017/fastbite
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your-super-secret-jwt-key
    depends_on:
      - mongo
      - redis
    networks:
      - fastbite-network

  # User Service
  user-service:
    build:
      context: ../backend/services/user-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - MONGO_URI=mongodb://mongo:27017/fastbite
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis
    networks:
      - fastbite-network

  # Restaurant Service
  restaurant-service:
    build:
      context: ../backend/services/restaurant-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PORT=3003
      - MONGO_URI=mongodb://mongo:27017/fastbite
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis
    networks:
      - fastbite-network

  # Order Service
  order-service:
    build:
      context: ../backend/services/order-service
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - PORT=3004
      - MONGO_URI=mongodb://mongo:27017/fastbite
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis
    networks:
      - fastbite-network

  # Payment Service
  payment-service:
    build:
      context: ../backend/services/payment-service
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - PORT=3005
      - MONGO_URI=mongodb://mongo:27017/fastbite
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - STRIPE_SECRET_KEY=your-stripe-secret-key
    depends_on:
      - mongo
      - redis
    networks:
      - fastbite-network

  # Delivery Service
  delivery-service:
    build:
      context: ../backend/services/delivery-service
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=production
      - PORT=3006
      - MONGO_URI=mongodb://mongo:27017/fastbite
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis
    networks:
      - fastbite-network

  # Notification Service
  notification-service:
    build:
      context: ../backend/services/notification-service
      dockerfile: Dockerfile
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=production
      - PORT=3007
      - MONGO_URI=mongodb://mongo:27017/fastbite
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TWILIO_ACCOUNT_SID=your-twilio-account-sid
      - TWILIO_AUTH_TOKEN=your-twilio-auth-token
      - SENDGRID_API_KEY=your-sendgrid-api-key
    depends_on:
      - mongo
      - redis
    networks:
      - fastbite-network

  # AI Service
  ai-service:
    build:
      context: ../backend/services/ai-service
      dockerfile: Dockerfile
    ports:
      - "3008:3008"
    environment:
      - NODE_ENV=production
      - PORT=3008
      - MONGO_URI=mongodb://mongo:27017/fastbite
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis
    networks:
      - fastbite-network

  # Analytics Service
  analytics-service:
    build:
      context: ../backend/services/analytics-service
      dockerfile: Dockerfile
    ports:
      - "3009:3009"
    environment:
      - NODE_ENV=production
      - PORT=3009
      - MONGO_URI=mongodb://mongo:27017/fastbite
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis
    networks:
      - fastbite-network

  # Restaurant Dashboard
  restaurant-dashboard:
    build:
      context: ../restaurant-dashboard
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api-gateway:3000/api
      - NEXT_PUBLIC_WS_URL=ws://api-gateway:3000
    depends_on:
      - api-gateway
    networks:
      - fastbite-network

  # MongoDB
  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=fastbite
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - fastbite-network

  # Redis
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - fastbite-network

  # Nginx (Reverse Proxy)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api-gateway
      - restaurant-dashboard
    networks:
      - fastbite-network

volumes:
  mongo_data:
  redis_data:

networks:
  fastbite-network:
    driver: bridge

